"""empty message

Revision ID: 131566c0517b
Revises: 06f4baf4b179
Create Date: 2023-07-21 16:09:54.508440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '131566c0517b'
down_revision = '06f4baf4b179'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('location')
        batch_op.drop_column('member_since')
        batch_op.drop_column('about_me')
        batch_op.drop_column('name')
        batch_op.drop_column('last_seen')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_seen', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=64), nullable=True))
        batch_op.add_column(sa.Column('about_me', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('member_since', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('location', sa.TEXT(length=64), nullable=True))

    # ### end Alembic commands ###
