"""empty message

Revision ID: 621596c6757e
Revises: 06655ab11157
Create Date: 2023-07-25 15:12:28.190960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '621596c6757e'
down_revision = '06655ab11157'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('body_html', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('body_html')

    # ### end Alembic commands ###
